services:
  linux-reporter:
    build: .

    container_name: linux-reporter

    ports:
      - "5000:5000"

    environment:
      SSH_KEY_PATH: /app/vault-keys/ec2-syd-ops-key.pem
      ANSIBLE_USER: root

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - /var/tmp/key-folder/ec2-syd-ops-key.pem:/app/vault-keys/ec2-syd-ops-key.pem:ro

    restart: unless-stopped
